// Code generated by github.com/wanjm/gos DO NOT EDIT.
package db

import (
	time "time"
)

// TableConstantConfig Database table constant type configuration table

// @gos tblName=table_constant_config dbVariable=db
type TableConstantConfig struct {
	ID int64 "json:\"id\" gorm:\"column:id\"" // Primary key ID

	TableName string "json:\"tableName\" gorm:\"column:table_name\"" // Associated database table name

	ColumnName string "json:\"columnName\" gorm:\"column:column_name\"" // Associated table column name

	ConstName string "json:\"constName\" gorm:\"column:const_name\"" // Custom name for the constant (string)

	Value int32 "json:\"value\" gorm:\"column:value\"" // Constant value (integer)

	ValueType int8 "json:\"valueType\" gorm:\"column:value_type\"" // Value type: 1=integer, 2=bit

	Meaning string "json:\"meaning\" gorm:\"column:meaning\"" // Meaning/description of the constant

	CreateTime time.Time "json:\"createTime\" gorm:\"column:create_time\"" // Creation time

}
