package flutter_gen

import (
	"fmt"
	"strings"

	"github.com/wanjm/gos/astinfo"
)

func collectReferencedEnums(s *astinfo.Struct, mp *astinfo.MainProject, seen map[string]*astinfo.EnumDef) {
	for _, field := range s.FlatFields() {
		if field.Comment.EnumName == "" {
			continue
		}
		enumDef := mp.LookupEnum(field.Comment.EnumName)
		if enumDef == nil {
			fmt.Printf("WARNING: enum %q not found for field %s::%s\n", field.Comment.EnumName, s.StructName, field.Name)
			continue
		}
		if _, ok := seen[enumDef.Name]; !ok {
			seen[enumDef.Name] = enumDef
		}
	}
}

func GenEnumDart(enum *astinfo.EnumDef) string {
	return genEnumDart(enum)
}

func genEnumDart(enum *astinfo.EnumDef) string {
	var sb strings.Builder
	valueType := enum.DartValueType()
	fromParam := nullableFromParam(enum.ValueKind)

	sb.WriteString(fmt.Sprintf("enum %s {\n", enum.Name))
	for i, m := range enum.Members {
		val := m.DartValueLiteral(enum.ValueKind)
		display := escapeDartString(m.DisplayWord)
		comma := ","
		if i == len(enum.Members)-1 {
			comma = ";"
		}
		fmt.Fprintf(&sb, "  %s(%s, '%s')%s\n", m.DartMemberName(), val, display, comma)
	}
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "  const %s(this.value, this.displayWord);\n", enum.Name)
	fmt.Fprintf(&sb, "  final %s value;\n", valueType)
	sb.WriteString("  final String displayWord;\n")
	sb.WriteString("  String text() => displayWord;\n\n")
	fmt.Fprintf(&sb, "  static %s? fromValue(%s v) {\n", enum.Name, fromParam)
	sb.WriteString("    if (v == null) return null;\n")
	sb.WriteString("    for (final e in values) {\n")
	sb.WriteString("      if (e.value == v) return e;\n")
	sb.WriteString("    }\n")
	sb.WriteString("    return null;\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return sb.String()
}

func nullableFromParam(kind string) string {
	switch kind {
	case "string":
		return "String?"
	case "bool":
		return "bool?"
	default:
		return "int?"
	}
}

func enumDefaultValue(enum *astinfo.EnumDef) string {
	if len(enum.Members) == 0 {
		return "null"
	}
	return enum.Name + "." + enum.Members[0].DartMemberName()
}

func enumParseExpr(enum *astinfo.EnumDef, jsonKey string) string {
	expr := jsonExprForKind(enum.ValueKind, jsonKey)
	return enum.Name + ".fromValue(" + expr + ")"
}

func jsonExprForKind(kind, jsonKey string) string {
	switch kind {
	case "string":
		return "json['" + jsonKey + "'] as String?"
	case "bool":
		return "json['" + jsonKey + "'] as bool?"
	default:
		return "(json['" + jsonKey + "'] as num?)?.toInt()"
	}
}

func enumToJsonExpr(fieldName string, enum *astinfo.EnumDef) string {
	_ = enum
	return fieldName + ".value"
}

func escapeDartString(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}

func genEnumFileContent(enums map[string]*astinfo.EnumDef) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n\n")
	names := sortedEnumNames(enums)
	for _, name := range names {
		sb.WriteString(genEnumDart(enums[name]))
		sb.WriteString("\n")
	}
	return sb.String()
}

func sortedEnumNames(enums map[string]*astinfo.EnumDef) []string {
	names := make([]string, 0, len(enums))
	for name := range enums {
		names = append(names, name)
	}
	for i := 0; i < len(names); i++ {
		for j := i + 1; j < len(names); j++ {
			if names[j] < names[i] {
				names[i], names[j] = names[j], names[i]
			}
		}
	}
	return names
}

func mapFieldType(field *astinfo.Field, mp *astinfo.MainProject, fallback func(astinfo.Typer) string) string {
	if field.Comment.EnumName != "" {
		if mp.LookupEnum(field.Comment.EnumName) != nil {
			return field.Comment.EnumName
		}
	}
	return fallback(field.Type)
}

func fieldDefaultAndParse(field *astinfo.Field, jsonKey string, mp *astinfo.MainProject, gen *FlutterGen) (defaultValue, parseString, toJsonExpr string) {
	if field.Comment.EnumName != "" {
		enumDef := mp.LookupEnum(field.Comment.EnumName)
		if enumDef != nil {
			dartName := jsonKey
			if jsonKey == "_id" {
				dartName = "id"
			}
			return enumDefaultValue(enumDef), enumParseExpr(enumDef, jsonKey) + " ?? " + enumDefaultValue(enumDef), enumToJsonExpr(dartName, enumDef)
		}
	}
	dv, ps := gen.defaultValue(field.Type, jsonKey)
	dartName := jsonKey
	if jsonKey == "_id" {
		dartName = "id"
	}
	return dv, ps, dartName
}
