package flutter_gen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
	"github.com/wanjm/gos/basic"
)

type FlutterGen struct {
}

func NewFlutterGen() *FlutterGen {
	return &FlutterGen{}
}

// DTOField represents a field in a DTO struct
type DTOField struct {
	Name         string
	Comment      string
	DartType     string
	DefaultValue string //构造函数中 this.xxx=${DefaultValue};
	// 在template中使用, 用于生成构造函数时，是否添加requred 关键字； requried this.XXX
	// 主要原因是不想在结构中有null，但是对于需要调用函数构造的，构造函数可能不支持const，所以不能卸载this.XXx= DeaultValue；
	// 目前只要是结构体，都添加required关键字；同时在fromJson中初始化
	Required    bool
	ParseString string
}

// DTOTemplateData holds the data for DTO template generation
type DTOTemplateData struct {
	StructName string
	Fields     []DTOField
}

// DTO generation template
const dtoTemplate = `// [{{range $i, $field := .Fields}}{{if $i}},{{end}}"{{$field.Name}}"{{end}}]
class {{.StructName}} extends JSONParameter {
{{range .Fields}} /// {{.Comment}}
 {{.DartType}} {{.Name}};
{{end}}
  {{.StructName}}({
{{range .Fields}} {{if .Required}} required this.{{.Name}} {{else}} this.{{.Name}} = {{.DefaultValue}}{{end}},
{{end}}
  });

  factory {{.StructName}}.fromJson(Map<String, dynamic> json) {
    return {{.StructName}}(
{{range .Fields}}   {{.Name}}: {{.ParseString}},
{{end}}    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
{{range .Fields}}      "{{.Name}}": {{.Name}},
{{end}}    };
  }
}
`

func (f *FlutterGen) GenerateCode(mp *astinfo.MainProject) {
	// 1. Determine output directory
	var outDir = basic.Cfg.Generation.FlutterPath
	if outDir == "" {
		return
	}
	// Handle relative paths: if not absolute, make it relative to SourcePath
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(basic.Argument.SourcePath, outDir)
	}
	// Convert to absolute path for consistency
	var err error
	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Printf("Failed to resolve flutter gen directory: %v\n", err)
		return
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Printf("Failed to create flutter gen directory: %v\n", err)
		return
	}

	// 2. Collect all services and referenced DTOs
	var allServices []*astinfo.Struct
	referencedStructs := make(map[string]*astinfo.Struct)

	for _, pkgName := range mp.SortedPacakgeNames {
		pkg := mp.Packages[pkgName]
		for _, structName := range pkg.SortedStructNames {
			s := pkg.Structs[structName]
			// Check if struct is a service (has methods marked as servlet/prpc)
			if len(s.MethodManager.Server) == 0 {
				continue
			}
			allServices = append(allServices, s)

			// Collect DTOs for this service
			for _, m := range s.MethodManager.Server {
				// Params
				for _, p := range m.Params {
					f.collectStructs(p.Type, referencedStructs)
				}
				// Results
				for _, r := range m.Results {
					f.collectStructs(r.Type, referencedStructs)
				}
			}
		}
	}

	// Sort services by name
	sort.Slice(allServices, func(i, j int) bool {
		return allServices[i].StructName < allServices[j].StructName
	})

	// 3. Generate files
	f.genSchemaFile(outDir, referencedStructs)
	f.genNetworkFile(outDir, allServices)
}

func (f *FlutterGen) genSchemaFile(outDir string, referencedStructs map[string]*astinfo.Struct) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import 'package:http_method/http_method.dart';\n\n")

	// Sort DTOs by name
	var structNames []string
	for name := range referencedStructs {
		structNames = append(structNames, name)
	}
	sort.Strings(structNames)

	for _, name := range structNames {
		s := referencedStructs[name]
		sb.WriteString(f.genDTO(s))
		sb.WriteString("\n")
	}

	os.WriteFile(filepath.Join(outDir, "schema.gen.dart"), []byte(sb.String()), 0644)
}

func (f *FlutterGen) genNetworkFile(outDir string, services []*astinfo.Struct) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import 'package:http_method/http_method.dart';\n")
	sb.WriteString("import 'schema.gen.dart';\n")
	sb.WriteString("import 'myclient.dart';\n\n")

	// Generate part directive for the consolidated file
	sb.WriteString("part 'network.gen.g.dart';\n\n")

	for _, s := range services {
		// Abstract class with @DataInterface() annotation
		sb.WriteString("@DataInterface()\n")
		sb.WriteString(fmt.Sprintf("abstract class %s {\n", s.StructName))

		// Sort methods by name
		methods := make([]*astinfo.Method, len(s.MethodManager.Server))
		copy(methods, s.MethodManager.Server)
		sort.Slice(methods, func(i, j int) bool {
			return methods[i].Name < methods[j].Name
		})

		for _, m := range methods {
			// Get URL from method comment, combine with struct url if needed
			url := m.Comment.Url
			fullUrl := strings.ReplaceAll(filepath.Join(s.Comment.Url, url), "\\", "/")
			urlFieldName := astbasic.FirstLower(m.Name) + "Url"

			fmt.Fprintf(&sb, "  /// %s\n", m.Comment.Title)
			fmt.Fprintf(&sb, "  static const String %s = \"%s\";\n", urlFieldName, fullUrl)
			fmt.Fprintf(&sb, "  /// %s\n", m.Comment.Title)
			// Add @ReqConfig annotation
			fmt.Fprintf(&sb, "  @ReqConfig(%s)\n", urlFieldName)

			respType := "void"
			// at lease one error result;
			if len(m.Results) > 1 {
				respType = f.mapType(m.Results[0].Type)
			}
			// If respType is dynamic, omit the type parameter entirely
			switch respType {
			case "dynamic":
				fmt.Fprintf(&sb, "  Future<RespData> %s(", astbasic.FirstLower(m.Name))
			case "void":
				// If respType is void, omit the ? (no nullable)
				fmt.Fprintf(&sb, "  Future<RespData<%s>> %s(", respType, astbasic.FirstLower(m.Name))
			default:
				fmt.Fprintf(&sb, "  Future<RespData<%s?>> %s(", respType, astbasic.FirstLower(m.Name))
			}

			// Params. Usually (Context, Request). Context is skipped.
			if len(m.Params) > 1 {
				reqType := f.mapType(m.Params[1].Type)
				sb.WriteString(fmt.Sprintf("%s data", reqType))
			}
			sb.WriteString(");\n")
		}
		sb.WriteString("}\n\n")
	}

	os.WriteFile(filepath.Join(outDir, "network.gen.dart"), []byte(sb.String()), 0644)
}

func (f *FlutterGen) collectStructs(t astinfo.Typer, seen map[string]*astinfo.Struct) {
	t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.Struct:
		if _, ok := seen[v.StructName]; !ok {
			if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
				return
			}
			seen[v.StructName] = v
			// Recursively collect fields
			for _, field := range v.Fields {
				f.collectStructs(field.Type, seen)
			}
		}
	case *astinfo.ArrayType:
		f.collectStructs(v.Typer, seen)
	case *astinfo.PointerType:
		f.collectStructs(v.Typer, seen)
	}
}

func (f *FlutterGen) genDTO(s *astinfo.Struct) string {
	// Collect fields for template
	flatFields := s.FlatFields()
	var fields []DTOField

	for _, field := range flatFields {
		name := field.GetJsonName()
		if name == "" || name == "-" {
			fmt.Printf("WARNING: field %s::%s %T is not a JSONParameter\n", field.Type.IDName(), field.Name, field.Type)
			continue
		}
		dartType := f.mapType(field.Type)
		var defaultValue string
		var parseString string
		if (name == "updateTime" || name == "createTime") && dartType == "int" {
			dartType = "DateTime"
			defaultValue = "DateTime.fromMillisecondsSinceEpoch(0)"
			parseString = "DateTime.fromMillisecondsSinceEpoch((json['" + name + "'] as num? ?? 0).toInt())"
		} else {
			defaultValue, parseString = f.defaultValue(field.Type, name)
		}
		fields = append(fields, DTOField{
			Name:         name,
			Comment:      field.Comment.CommentText,
			DartType:     dartType,
			DefaultValue: defaultValue,
			ParseString:  parseString,
			Required:     strings.HasSuffix(defaultValue, ")"), //defaultValu以")"结尾表示这是结构体；
		})
	}

	// Prepare template data
	data := DTOTemplateData{
		StructName: s.StructName,
		Fields:     fields,
	}

	// Parse and execute template
	var sb strings.Builder
	tpl, err := template.New("dto").Parse(dtoTemplate)
	if err != nil {
		panic(fmt.Sprintf("Failed to parse DTO template: %v", err))
	}
	if err := tpl.Execute(&sb, data); err != nil {
		panic(fmt.Sprintf("Failed to execute DTO template: %v", err))
	}

	return sb.String()
}

func (f *FlutterGen) mapType(t astinfo.Typer) string {
	// t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "String"
		case "byte", "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16":
			return "int"
		case "float32", "float64":
			return "double"
		case "bool":
			return "bool"
		default:
			return "dynamic"
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "String"
			}
		}
		subName := f.mapType(v.Typer)
		return "List<" + subName + ">"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "DateTime"
		}
		return v.StructName
	case *astinfo.PointerType:
		return f.mapType(v.Typer)
	case *astinfo.Alias:
		return f.mapType(v.Typer)
	default:
		return "dynamic"
	}
}

func isBasicType(t string) bool {
	switch t {
	case "String", "int", "double", "bool", "dynamic":
		return true
	}
	return false
}

func (f *FlutterGen) genTypeParse(t astinfo.Typer, expr string) string {
	bt := astinfo.GetBasicType(t)
	switch v := bt.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return expr + " as String? ?? \"\""
		case "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16", "byte":
			return "(" + expr + " as num? ?? 0).toInt()"
		case "float32", "float64":
			return "(" + expr + " as num? ?? 0.0).toDouble()"
		case "bool":
			return expr + " ?? false"
		default:
			return expr
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return expr + "?.toString() ?? \"\""
			}
		}
		elemType := v.Typer
		elemParse := f.genTypeParse(elemType, "e")
		return "(" + expr + " as List? ?? []).map((e) => " + elemParse + ").toList()"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return expr + " != null && " + expr + ".toString().isNotEmpty ? DateTime.parse(" + expr + ".toString()) : DateTime.fromMillisecondsSinceEpoch(0)"
		}
		return v.StructName + ".fromJson(" + expr + " ?? {})"
	default:
		return expr
	}
}

func (f *FlutterGen) genTypeDefault(t astinfo.Typer) string {
	bt := astinfo.GetBasicType(t)
	switch v := bt.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "\"\""
		case "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16", "byte":
			return "0"
		case "float32", "float64":
			return "0.0"
		case "bool":
			return "false"
		default:
			return "null"
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "\"\""
			}
		}
		return "const []"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "DateTime.fromMillisecondsSinceEpoch(0)"
		}
		return v.StructName + ".fromJson({})"
	default:
		return "null"
	}
}

// defaultValue 是默认值；
// parseString 是解析字符串；FromJson重的字符串 (json['status'] as num? ?? 0).toInt()
func (f *FlutterGen) defaultValue(t astinfo.Typer, fieldName string) (defaultValue string, parseString string) {
	defaultValue = f.genTypeDefault(t)
	parseString = f.genTypeParse(t, "json['"+fieldName+"']")
	return
}
