package flutter_gen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
	"github.com/wanjm/gos/basic"
)

type FlutterGen struct {
}

func NewFlutterGen() *FlutterGen {
	return &FlutterGen{}
}

// DTOField represents a field in a DTO struct
type DTOField struct {
	Name         string // Dart field / constructor name (e.g. "id", never "_id" — private in Dart)
	JsonKey      string // JSON map key from API/Mongo (e.g. "_id"); empty means same as Name
	Comment      string
	DartType     string
	DefaultValue string //构造函数中 this.xxx=${DefaultValue};
	// 在template中使用, 用于生成构造函数时，是否添加requred 关键字； requried this.XXX
	// 主要原因是不想在结构中有null，但是对于需要调用函数构造的，构造函数可能不支持const，所以不能卸载this.XXx= DeaultValue；
	// 目前只要是结构体，都添加required关键字；同时在fromJson中初始化
	Required    bool
	ParseString string //
	ToJsonExpr  string // 用于生成toJson()方法中的表达式；由变量本身和 enum.value两种写法；
}

// DTOTemplateData holds the data for DTO template generation
type DTOTemplateData struct {
	StructName string
	Fields     []DTOField
}

// DTO generation template
const dtoTemplate = `// [{{range $i, $field := .Fields}}{{if $i}},{{end}}"{{$field.Name}}"{{end}}]
class {{.StructName}} extends JSONParameter {
{{range .Fields}} /// {{.Comment}}
 {{.DartType}} {{.Name}};
{{end}}
{{if .Fields}}
  {{.StructName}}({
{{range .Fields}} {{if .Required}} required this.{{.Name}} {{else}} this.{{.Name}} = {{.DefaultValue}}{{end}},
{{end}}
  });
{{else}}
  {{.StructName}}();
{{end}}

  factory {{.StructName}}.fromJson(Map<String, dynamic> json) {
    return {{.StructName}}(
{{range .Fields}}   {{.Name}}: {{.ParseString}},
{{end}}    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
{{range .Fields}}      "{{.JsonKey}}": {{.ToJsonExpr}},
{{end}}    };
  }
}
`

func (f *FlutterGen) GenerateCode(mp *astinfo.MainProject) {
	// 1. Determine output directory
	var outDir = basic.Cfg.Generation.FlutterPath
	if outDir == "" {
		return
	}
	// Handle relative paths: if not absolute, make it relative to SourcePath
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(basic.Argument.SourcePath, outDir)
	}
	// Convert to absolute path for consistency
	var err error
	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Printf("Failed to resolve flutter gen directory: %v\n", err)
		return
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Printf("Failed to create flutter gen directory: %v\n", err)
		return
	}

	// 2. Collect all services and referenced DTOs
	var allServices []*astinfo.Struct
	referencedStructs := make(map[string]*astinfo.Struct)
	referencedEnums := make(map[string]*astinfo.EnumDef)

	for _, pkgName := range mp.SortedPacakgeNames {
		pkg := mp.Packages[pkgName]
		for _, structName := range pkg.SortedStructNames {
			s := pkg.Structs[structName]
			// Check if struct is a service (has methods marked as servlet/prpc)
			if len(s.MethodManager.Server) == 0 {
				continue
			}
			allServices = append(allServices, s)

			// Collect DTOs for this service
			for _, m := range s.MethodManager.Server {
				// Params
				for _, p := range m.Params {
					f.collectStructs(p.Type, referencedStructs, mp, referencedEnums)
				}
				// Results
				for _, r := range m.Results {
					f.collectStructs(r.Type, referencedStructs, mp, referencedEnums)
				}
			}
		}
	}

	// Sort services by name
	sort.Slice(allServices, func(i, j int) bool {
		return allServices[i].StructName < allServices[j].StructName
	})

	// 3. Generate files — all @gos enum const blocks go to enum.gen.dart
	allEnums := mp.EnumMap
	if len(allEnums) > 0 {
		f.genEnumFile(outDir, allEnums)
	}
	f.genSchemaFile(outDir, referencedStructs, len(referencedEnums) > 0, mp)
	f.genNetworkFile(outDir, allServices)
}

func (f *FlutterGen) genEnumFile(outDir string, referencedEnums map[string]*astinfo.EnumDef) {
	os.WriteFile(filepath.Join(outDir, "enum.gen.dart"), []byte(genEnumFileContent(referencedEnums)), 0644)
}

func (f *FlutterGen) genSchemaFile(outDir string, referencedStructs map[string]*astinfo.Struct, importEnums bool, mp *astinfo.MainProject) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import 'package:component_set/component_set.dart';\n")
	if importEnums {
		sb.WriteString("import 'enum.gen.dart';\n")
	}
	sb.WriteString("\n")

	// Sort DTOs by name
	var structNames []string
	for name := range referencedStructs {
		structNames = append(structNames, name)
	}
	sort.Strings(structNames)

	for _, name := range structNames {
		s := referencedStructs[name]
		sb.WriteString(f.genDTO(s, mp))
		sb.WriteString("\n")
	}

	os.WriteFile(filepath.Join(outDir, "schema.gen.dart"), []byte(sb.String()), 0644)
}

func (f *FlutterGen) genNetworkFile(outDir string, services []*astinfo.Struct) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import 'package:component_set/component_set.dart';\n")
	sb.WriteString("import 'package:component_generator/component_generator.dart';\n")
	sb.WriteString("import 'schema.gen.dart';\n")
	sb.WriteString("import 'myclient.dart';\n\n")

	// Generate part directive for the consolidated file
	sb.WriteString("part 'network.gen.g.dart';\n\n")

	for _, s := range services {
		// Abstract class with @DataInterface() annotation
		sb.WriteString("@DataInterface()\n")
		sb.WriteString(fmt.Sprintf("abstract class %s {\n", s.StructName))

		// Sort methods by name
		methods := make([]*astinfo.Method, len(s.MethodManager.Server))
		copy(methods, s.MethodManager.Server)
		sort.Slice(methods, func(i, j int) bool {
			return methods[i].Name < methods[j].Name
		})

		for _, m := range methods {
			// Get URL from method comment, combine with struct url if needed
			url := m.Comment.Url
			fullUrl := strings.ReplaceAll(filepath.Join(s.Comment.Url, url), "\\", "/")
			urlFieldName := astbasic.FirstLower(m.Name) + "Url"

			fmt.Fprintf(&sb, "  /// %s\n", m.Comment.Title)
			fmt.Fprintf(&sb, "  static const String %s = \"%s\";\n", urlFieldName, fullUrl)
			fmt.Fprintf(&sb, "  /// %s\n", m.Comment.Title)
			// Add @ReqConfig annotation
			fmt.Fprintf(&sb, "  @ReqConfig(%s)\n", urlFieldName)

			respType := "void"
			// at lease one error result;
			if len(m.Results) > 1 {
				respType = f.mapType(m.Results[0].Type)
			}
			// If respType is dynamic, omit the type parameter entirely
			switch respType {
			case "dynamic":
				fmt.Fprintf(&sb, "  Future<RespData> %s(", astbasic.FirstLower(m.Name))
			case "void":
				// If respType is void, omit the ? (no nullable)
				fmt.Fprintf(&sb, "  Future<RespData<%s>> %s(", respType, astbasic.FirstLower(m.Name))
			default:
				fmt.Fprintf(&sb, "  Future<RespData<%s?>> %s(", respType, astbasic.FirstLower(m.Name))
			}

			// Params. Usually (Context, Request). Context is skipped.
			if len(m.Params) > 1 {
				reqType := f.mapType(m.Params[1].Type)
				sb.WriteString(fmt.Sprintf("%s data", reqType))
			}
			sb.WriteString(");\n")
		}
		sb.WriteString("}\n\n")
	}

	os.WriteFile(filepath.Join(outDir, "network.gen.dart"), []byte(sb.String()), 0644)
}

func (f *FlutterGen) collectStructs(t astinfo.Typer, seen map[string]*astinfo.Struct, mp *astinfo.MainProject, referencedEnums map[string]*astinfo.EnumDef) {
	t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.Struct:
		if _, ok := seen[v.StructName]; !ok {
			if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
				return
			}
			seen[v.StructName] = v
			collectReferencedEnums(v, mp, referencedEnums)
			// Recursively collect fields
			for _, field := range v.Fields {
				f.collectStructs(field.Type, seen, mp, referencedEnums)
			}
		}
	case *astinfo.ArrayType:
		f.collectStructs(v.Typer, seen, mp, referencedEnums)
	case *astinfo.PointerType:
		f.collectStructs(v.Typer, seen, mp, referencedEnums)
	}
}

func (f *FlutterGen) genDTO(s *astinfo.Struct, mp *astinfo.MainProject) string {
	return renderDTOTemplate(DTOTemplateData{
		StructName: s.StructName,
		Fields:     f.buildDTOFields(s, mp),
	})
}

func (f *FlutterGen) buildDTOFields(s *astinfo.Struct, mp *astinfo.MainProject) []DTOField {
	var fields []DTOField
	for _, field := range s.FlatFields() {
		dto, ok := f.newDTOField(field, mp)
		if !ok {
			continue
		}
		fields = append(fields, dto)
	}
	return fields
}

func (f *FlutterGen) newDTOField(field *astinfo.Field, mp *astinfo.MainProject) (DTOField, bool) {
	jsonKey := field.GetJsonName()
	if jsonKey == "" || jsonKey == "-" {
		fmt.Printf("WARNING: field %s::%s %T is not a JSONParameter\n", field.Type.IDName(), field.Name, field.Type)
		return DTOField{}, false
	}

	defaultValue, parseString := f.defaultValue(field.Type, jsonKey)
	dto := DTOField{
		Name:         jsonKey,
		JsonKey:      jsonKey,
		Comment:      field.Comment.CommentText,
		DartType:     f.mapFieldType(field, mp),
		DefaultValue: defaultValue,
		ParseString:  parseString,
		ToJsonExpr:   jsonKey,
	}

	f.applyMongoIDCase(&dto)
	f.applyEpochMillisTimeCase(&dto)
	f.applyEnumCase(&dto, field, mp)
	dto.Required = strings.HasSuffix(dto.DefaultValue, ")") // defaultValue以")"结尾表示这是结构体；
	return dto, true
}

func (f *FlutterGen) applyMongoIDCase(dto *DTOField) {
	if dto.JsonKey != "_id" {
		return
	}
	dto.Name = "id"
	dto.ToJsonExpr = "id"
}

func (f *FlutterGen) applyEpochMillisTimeCase(dto *DTOField) {
	if dto.DartType != "int" || !jsonKeyEpochMillisTime(dto.JsonKey) {
		return
	}
	dto.DartType = "DateTime"
	dto.DefaultValue = "DateTime.fromMillisecondsSinceEpoch(0)"
	dto.ParseString = "DateTime.fromMillisecondsSinceEpoch((json['" + dto.JsonKey + "'] as num? ?? 0).toInt())"
	dto.ToJsonExpr = dto.Name
}

func (f *FlutterGen) applyEnumCase(dto *DTOField, field *astinfo.Field, mp *astinfo.MainProject) {
	if field.Comment.EnumName == "" {
		return
	}
	enumDef := mp.LookupEnum(field.Comment.EnumName)
	if enumDef == nil {
		return
	}
	defaultValue := enumDef.DartDefaultValue()
	dto.DartType = field.Comment.EnumName
	dto.DefaultValue = defaultValue
	dto.ParseString = enumDef.DartParseExpr(dto.JsonKey) + " ?? " + defaultValue
	dto.ToJsonExpr = enumDef.DartToJSONExpr(dto.Name)
}

func renderDTOTemplate(data DTOTemplateData) string {
	var sb strings.Builder
	tpl, err := template.New("dto").Parse(dtoTemplate)
	if err != nil {
		panic(fmt.Sprintf("Failed to parse DTO template: %v", err))
	}
	if err := tpl.Execute(&sb, data); err != nil {
		panic(fmt.Sprintf("Failed to execute DTO template: %v", err))
	}

	return sb.String()
}

// jsonKeyEpochMillisTime is true when the JSON key names a Unix-ms epoch field
// (Go int*); those map to Dart DateTime via fromMillisecondsSinceEpoch.
func jsonKeyEpochMillisTime(jsonKey string) bool {
	return strings.HasSuffix(jsonKey, "At") || strings.HasSuffix(jsonKey, "Time")
}

func (f *FlutterGen) mapType(t astinfo.Typer) string {
	// t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "String"
		case "byte", "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16":
			return "int"
		case "float32", "float64":
			return "double"
		case "bool":
			return "bool"
		default:
			return "dynamic"
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "String"
			}
		}
		subName := f.mapType(v.Typer)
		return "List<" + subName + ">"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "DateTime"
		}
		return v.StructName
	case *astinfo.PointerType:
		return f.mapType(v.Typer)
	case *astinfo.Alias:
		return f.mapType(v.Typer)
	default:
		return "dynamic"
	}
}

func isBasicType(t string) bool {
	switch t {
	case "String", "int", "double", "bool", "dynamic":
		return true
	}
	return false
}

func (f *FlutterGen) genTypeParse(t astinfo.Typer, expr string) string {
	bt := astinfo.GetBasicType(t)
	switch v := bt.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return expr + " as String? ?? \"\""
		case "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16", "byte":
			return "(" + expr + " as num? ?? 0).toInt()"
		case "float32", "float64":
			return "(" + expr + " as num? ?? 0.0).toDouble()"
		case "bool":
			return expr + " ?? false"
		default:
			return expr
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return expr + "?.toString() ?? \"\""
			}
		}
		elemType := v.Typer
		elemParse := f.genTypeParse(elemType, "e")
		return "(" + expr + " as List? ?? []).map((e) => " + elemParse + ").toList()"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return expr + " != null && " + expr + ".toString().isNotEmpty ? DateTime.parse(" + expr + ".toString()) : DateTime.fromMillisecondsSinceEpoch(0)"
		}
		return v.StructName + ".fromJson(" + expr + " ?? {})"
	default:
		return expr
	}
}

func (_ *FlutterGen) genTypeDefault(t astinfo.Typer) string {
	bt := astinfo.GetBasicType(t)
	switch v := bt.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "\"\""
		case "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16", "byte":
			return "0"
		case "float32", "float64":
			return "0.0"
		case "bool":
			return "false"
		default:
			return "null"
		}
	case *astinfo.ArrayType:
		// Check for []byte or []uint8
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "\"\""
			}
		}
		return "const []"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "DateTime.fromMillisecondsSinceEpoch(0)"
		}
		return v.StructName + ".fromJson({})"
	default:
		return "null"
	}
}

// defaultValue 是默认值；
// parseString 是解析字符串；FromJson重的字符串 (json['status'] as num? ?? 0).toInt()
func (f *FlutterGen) defaultValue(t astinfo.Typer, fieldName string) (defaultValue string, parseString string) {
	defaultValue = f.genTypeDefault(t)
	parseString = f.genTypeParse(t, "json['"+fieldName+"']")
	return
}
