package flutter_gen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
	"github.com/wanjm/gos/basic"
)

type FlutterGen struct {
}

func NewFlutterGen() *FlutterGen {
	return &FlutterGen{}
}

// DTOField represents a field in a DTO struct
type DTOField struct {
	Name         string
	DartType     string
	DefaultValue string
	Required     bool
	ParseString  string
}

// DTOTemplateData holds the data for DTO template generation
type DTOTemplateData struct {
	StructName string
	Fields     []DTOField
}

// DTO generation template
const dtoTemplate = `class {{.StructName}} extends JSONParameter {
{{range .Fields}}  {{.DartType}} {{.Name}};
{{end}}
  {{.StructName}}({
{{range .Fields}}   
 {{if .Required}} required this.{{.Name}} {{else}} this.{{.Name}} = {{.DefaultValue}}{{end}},
{{end}}
  });

  factory {{.StructName}}.fromJson(Map<String, dynamic> json) {
    return {{.StructName}}(
{{range .Fields}}   {{.Name}}: {{.ParseString}},
{{end}}    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
{{range .Fields}}      "{{.Name}}": {{.Name}},
{{end}}    };
  }
}
`

func (f *FlutterGen) GenerateCode(mp *astinfo.MainProject) {
	// 1. Determine output directoroy
	var outDir = basic.Cfg.Generation.FlutterPath
	if outDir == "" {
		return
	}
	// Handle relative paths: if not absolute, make it relative to SourcePath
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(basic.Argument.SourcePath, outDir)
	}
	// Convert to absolute path for consistency
	var err error
	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Printf("Failed to resolve flutter gen directory: %v\n", err)
		return
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Printf("Failed to create flutter gen directory: %v\n", err)
		return
	}

	// 2. Iterate over packages and structs to generate services
	for _, pkgName := range mp.SortedPacakgeNames {
		pkg := mp.Packages[pkgName]
		for _, structName := range pkg.SortedStructNames {
			s := pkg.Structs[structName]
			// Check if struct is a service (has methods marked as servlet/prpc)
			// The prompt says: // @gos type=servlet; url="/example" on struct
			// We can also check s.Comment.serverType or groupName
			if len(s.MethodManager.Server) == 0 {
				continue
			}

			// Even if struct itself isn't marked as servlet, if it has server methods, we might want to generate it?
			// Usually the struct is the receiver for methods.
			f.genServiceInterface(outDir, s)
		}
	}
}

func (f *FlutterGen) genServiceInterface(outDir string, s *astinfo.Struct) {
	var sb strings.Builder

	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import 'package:http_method/http_method.dart';\n")
	sb.WriteString("import 'myclient.dart';\n\n")

	// Generate part directive for the .g.dart file
	fileName := strings.ToLower(s.StructName) + ".gen"
	sb.WriteString(fmt.Sprintf("part '%s.g.dart';\n\n", fileName))
	fileName = fileName + ".dart"
	// Collect dependent structs to generate them in the same file or import them
	// For simplicity, we'll try to generate DTOs used in this service in the same file,
	// or assume they are basic types.
	// A better approach is to collect all DTOs and generate them, but let's look at dependencies.

	// We need to track which structs have been generated to avoid duplication if we put them in one file.
	// But if we do per-service file, we might duplicate DTOs or need a shared DTO file.
	// Given the prompt "generate flutter call code", let's put DTOs used by the service in the same file for now,
	// ignoring cross-service sharing complexity (or maybe the user wants one big file?).
	// The prompt implies a file per service logic.

	// Let's find referenced structs
	referencedStructs := make(map[string]*astinfo.Struct)

	for _, m := range s.MethodManager.Server {
		// Params
		for _, p := range m.Params {
			f.collectStructs(p.Type, referencedStructs)
		}
		// Results
		for _, r := range m.Results {
			f.collectStructs(r.Type, referencedStructs)
		}
	}

	// Generate Structs
	for _, rs := range referencedStructs {
		// Don't generate the service struct itself as a DTO unless it is used as one?
		// Usually the service struct (Hello) is just a receiver.
		if rs == s {
			continue
		}
		sb.WriteString(f.genDTO(rs))
		sb.WriteString("\n")
	}

	// Generate Interface
	serviceName := s.StructName
	if s.Comment.GroupName != "" && s.Comment.GroupName != "servlet" {
		// Use group name if reasonable, but StructName is safer for uniqueness
		// serviceName = astbasic.Capitalize(s.Comment.GroupName)
	}

	// Abstract class with @DataInterface() annotation
	sb.WriteString("@DataInterface()\n")
	sb.WriteString(fmt.Sprintf("abstract class %s {\n", serviceName))
	for _, m := range s.MethodManager.Server {
		// Get URL from method comment, combine with struct url if needed
		url := m.Comment.Url
		fullUrl := strings.ReplaceAll(filepath.Join(s.Comment.Url, url), "\\", "/")

		// Add @ReqConfig annotation
		fmt.Fprintf(&sb, "  @ReqConfig(\"%s\")\n", fullUrl)

		respType := "void"
		// at lease one error result;
		if len(m.Results) > 1 {
			respType = f.mapType(m.Results[0].Type)
			// If result is object, mapType returns the name.
			// We want RespData<T?>
		}
		// If respType is dynamic, omit the type parameter entirely
		switch respType {
		case "dynamic":
			fmt.Fprintf(&sb, "  Future<RespData> %s(", astbasic.FirstLower(m.Name))
		case "void":
			// If respType is void, omit the ? (no nullable)
			fmt.Fprintf(&sb, "  Future<RespData<%s>> %s(", respType, astbasic.FirstLower(m.Name))
		default:
			fmt.Fprintf(&sb, "  Future<RespData<%s?>> %s(", respType, astbasic.FirstLower(m.Name))
		}

		// Params. Usually (Context, Request). Context is skipped.
		// Assuming 2nd param is Request.
		if len(m.Params) > 1 {
			reqType := f.mapType(m.Params[1].Type)
			sb.WriteString(fmt.Sprintf("%s data", reqType))
		}
		sb.WriteString(");\n")
	}
	sb.WriteString("}\n")

	os.WriteFile(filepath.Join(outDir, fileName), []byte(sb.String()), 0644)
}

func (f *FlutterGen) collectStructs(t astinfo.Typer, seen map[string]*astinfo.Struct) {
	t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.Struct:
		if _, ok := seen[v.StructName]; !ok {
			if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
				return
			}
			seen[v.StructName] = v
			// Recursively collect fields
			for _, field := range v.Fields {
				f.collectStructs(field.Type, seen)
			}
		}
	case *astinfo.ArrayType:
		f.collectStructs(v.Typer, seen)
	case *astinfo.PointerType:
		f.collectStructs(v.Typer, seen)
	}
}

func (f *FlutterGen) genDTO(s *astinfo.Struct) string {
	// Collect fields for template
	flatFields := s.FlatFields()
	var fields []DTOField

	for _, field := range flatFields {
		name := field.GetJsonName()
		if name == "" || name == "-" {
			fmt.Printf("WARNING: field %s::%s %T is not a JSONParameter\n", field.Type.IDName(), field.Name, field.Type)
			continue
		}
		dartType := f.mapType(field.Type)
		defaultValue, parseString := f.defaultValue(dartType, name)
		fields = append(fields, DTOField{
			Name:         name,
			DartType:     dartType,
			DefaultValue: defaultValue,
			Required:     strings.HasSuffix(defaultValue, ")"),
			ParseString:  parseString,
		})
	}

	// Prepare template data
	data := DTOTemplateData{
		StructName: s.StructName,
		Fields:     fields,
	}

	// Parse and execute template
	var sb strings.Builder
	tpl, err := template.New("dto").Parse(dtoTemplate)
	if err != nil {
		panic(fmt.Sprintf("Failed to parse DTO template: %v", err))
	}
	if err := tpl.Execute(&sb, data); err != nil {
		panic(fmt.Sprintf("Failed to execute DTO template: %v", err))
	}

	return sb.String()
}

func (f *FlutterGen) mapType(t astinfo.Typer) string {
	// t = astinfo.GetBasicType(t)
	switch v := t.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "String"
		case "byte":
			return "Uint8"
		case "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16":
			return "int"
		case "float32", "float64":
			return "double"
		case "bool":
			return "bool"
		default:
			return "dynamic"
		}
	case *astinfo.ArrayType:
		subName := f.mapType(v.Typer)
		if subName == "Uint8" {
			return "String"
		}
		return "List<" + subName + ">"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "DateTime"
		}
		return v.StructName //+ "?"
	case *astinfo.PointerType:
		va := f.mapType(v.Typer)
		return va
		// if strings.HasSuffix(va, "?") {
		// 	return va
		// }
		// return va + "?"
	case *astinfo.Alias:
		return f.mapType(v.Typer)
	default:
		return "dynamic"
	}
}

func isBasicType(t string) bool {
	switch t {
	case "String", "int", "double", "bool", "dynamic":
		return true
	}
	return false
}

func (f *FlutterGen) defaultValue(dartType string, fieldName string) (defaultValue string, parseString string) {
	if strings.HasPrefix(dartType, "List") {
		defaultValue = "const []"
		parseString = "((json['" + fieldName + "'] ?? []) as List).map((e) => " + dartType + ".fromJson(e)).toList()"
		return
	}

	switch dartType {
	case "String":
		defaultValue = "\"\""
		parseString = "json['" + fieldName + "'] ?? " + defaultValue
	case "int":
		defaultValue = "0"
		parseString = "json['" + fieldName + "'] ?? " + defaultValue
	case "double":
		defaultValue = "0.0"
		parseString = "json['" + fieldName + "'] ?? " + defaultValue
	case "bool":
		defaultValue = "false"
		parseString = "json['" + fieldName + "'] ?? " + defaultValue
	case "DateTime":
		defaultValue = "DateTime.fromMillisecondsSinceEpoch(0)"
		parseString = "DateTime.fromMillisecondsSinceEpoch(json['" + fieldName + "'] ?? 0)"
	default:
		defaultValue = dartType + ".fromJson({})"
		parseString = dartType + ".fromJson(json['" + fieldName + "'] ?? {})"
	}
	return
}
