package ts_gen

import (
	"fmt"
	"strings"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
)

func collectReferencedEnums(s *astinfo.Struct, mp *astinfo.MainProject, seen map[string]*astinfo.EnumDef) {
	for _, field := range s.FlatFields() {
		if field.Comment.EnumName == "" {
			continue
		}
		enumDef := mp.LookupEnum(field.Comment.EnumName)
		if enumDef == nil {
			fmt.Printf("WARNING: enum %q not found for field %s::%s\n", field.Comment.EnumName, s.StructName, field.Name)
			continue
		}
		if _, ok := seen[enumDef.Name]; !ok {
			seen[enumDef.Name] = enumDef
		}
	}
}

func GenEnumTS(enum *astinfo.EnumDef) string {
	return genEnumTS(enum)
}

func genEnumTS(enum *astinfo.EnumDef) string {
	var sb strings.Builder
	textHelper := astbasic.FirstLower(enum.Name) + "Text"
	recordKey := enum.TSValueType()

	switch enum.ValueKind {
	case "string":
		fmt.Fprintf(&sb, "export const %s = {\n", enum.Name)
		for i, m := range enum.Members {
			comma := ","
			if i == len(enum.Members)-1 {
				comma = ""
			}
			fmt.Fprintf(&sb, "  %s: %s%s\n", m.TSMemberName(), m.TSValueLiteral(enum.ValueKind), comma)
		}
		sb.WriteString("} as const;\n")
		fmt.Fprintf(&sb, "export type %s = typeof %s[keyof typeof %s];\n\n", enum.Name, enum.Name, enum.Name)
	default:
		fmt.Fprintf(&sb, "export enum %s {\n", enum.Name)
		for i, m := range enum.Members {
			comma := ","
			if i == len(enum.Members)-1 {
				comma = ""
			}
			fmt.Fprintf(&sb, "  %s = %s%s\n", m.TSMemberName(), m.TSValueLiteral(enum.ValueKind), comma)
		}
		sb.WriteString("}\n\n")
	}

	sb.WriteString(fmt.Sprintf("const %sDisplayWord: Record<%s, string> = {\n", enum.Name, recordKey))
	for i, m := range enum.Members {
		comma := ","
		if i == len(enum.Members)-1 {
			comma = ""
		}
		var key string
		if enum.ValueKind == "string" {
			key = m.TSValueLiteral(enum.ValueKind)
		} else {
			key = enum.Name + "." + m.TSMemberName()
		}
		fmt.Fprintf(&sb, "  [%s]: '%s'%s\n", key, escapeTSString(m.DisplayWord), comma)
	}
	sb.WriteString("};\n\n")
	fmt.Fprintf(&sb, "export function %s(v: %s): string {\n", textHelper, enum.Name)
	if enum.ValueKind == "string" {
		fmt.Fprintf(&sb, "  return %sDisplayWord[v] ?? '';\n", enum.Name)
	} else {
		fmt.Fprintf(&sb, "  return %sDisplayWord[v as number] ?? '';\n", enum.Name)
	}
	return sb.String()
}

func genEnumFileContent(enums map[string]*astinfo.EnumDef) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n\n")
	names := sortedEnumNames(enums)
	for _, name := range names {
		sb.WriteString(genEnumTS(enums[name]))
		sb.WriteString("\n")
	}
	return sb.String()
}

func sortedEnumNames(enums map[string]*astinfo.EnumDef) []string {
	names := make([]string, 0, len(enums))
	for name := range enums {
		names = append(names, name)
	}
	for i := 0; i < len(names); i++ {
		for j := i + 1; j < len(names); j++ {
			if names[j] < names[i] {
				names[i], names[j] = names[j], names[i]
			}
		}
	}
	return names
}

func mapFieldType(field *astinfo.Field, mp *astinfo.MainProject, fallback func(astinfo.Typer) string) string {
	if field.Comment.EnumName != "" {
		if mp.LookupEnum(field.Comment.EnumName) != nil {
			return field.Comment.EnumName
		}
	}
	return fallback(field.Type)
}

func escapeTSString(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}
