package ts_gen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
	"github.com/wanjm/gos/basic"
)

type TsGen struct{}

func NewTsGen() *TsGen {
	return &TsGen{}
}

const tsLibTemplate = `// Code generated by github.com/wanjm/gos DO NOT EDIT.
import { callApi as platformCallApi } from "./platform";
import type { CallApiInit } from "./call-api";

interface ApiResponse<T> {
  code: number;
  msg: string;
  obj: T;
}

export class RespClass<T> {
  code: number;
  msg: string;
  body: T;

  constructor(code: number, msg: string, body: T) {
    this.code = code;
    this.msg = msg;
    this.body = body;
  }

  isSuccess(): boolean {
    return this.code === 0;
  }
}

export async function callApi<T>(
  url: string,
  requestData: unknown,
  init?: CallApiInit,
): Promise<RespClass<T>> {
  try {
    const method = init?.method ?? "POST";
    const headers: Record<string, string> = { ...(init?.headers ?? {}) };
    if (method.toUpperCase() === "POST") {
      const hasContentType = Object.keys(headers).some(
        (key) => key.toLowerCase() === "content-type",
      );
      if (!hasContentType) {
        headers["Content-Type"] = "application/json";
      }
    }
    const res = await platformCallApi(url, {
      method,
      headers,
      body: init?.body ?? JSON.stringify(requestData),
      timeout: init?.timeout ?? 10000,
    });
    if (!res.ok) throw new Error("请求失败 " + res.status);
    const data = (await res.json()) as ApiResponse<T>;
    return new RespClass<T>(data.code, data.msg, data.obj);
  } catch (e) {
    const err = e as Error;
    return new RespClass<T>(-1, err.message, null as T);
  }
}
`

// call-api.ts / platform.ts / pc.ts / wx.ts are written only when missing so
// projects can switch the platform import and customize transport without losing edits.

const callApiTsTemplate = `// Shared callApi types. Written once by gos; edit freely.

export type CallApiInit = {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
  /** Timeout in milliseconds. */
  timeout?: number;
};

export type CallApiResponse = {
  ok: boolean;
  status: number;
  json(): Promise<unknown>;
};
`

const platformTsTemplate = `// Written once by gos; edit freely.
// Switch platform by changing which file is re-exported.
export type { CallApiInit, CallApiResponse } from "./call-api";
export { callApi } from "./pc";
// export { callApi } from "./wx";
`

const pcTsTemplate = `// Browser / Node fetch transport. Written once by gos; edit freely.
import type { CallApiInit, CallApiResponse } from "./call-api";

/** Fetch-like HTTP call without AbortSignal; timeout is handled internally. */
export async function callApi(input: string, init?: CallApiInit): Promise<CallApiResponse> {
  const timeout = init?.timeout ?? 10000;
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);
  try {
    const res = await fetch(input, {
      method: init?.method,
      headers: init?.headers,
      body: init?.body,
      signal: controller.signal,
    });
    return {
      ok: res.ok,
      status: res.status,
      json: () => res.json(),
    };
  } catch (e) {
    const err = e as Error;
    throw new Error(err.name === "AbortError" ? "请求超时" : err.message);
  } finally {
    clearTimeout(timeoutId);
  }
}
`

const wxTsTemplate = `// WeChat Mini Program transport. Written once by gos; edit freely.
import type { CallApiInit, CallApiResponse } from "./call-api";

/** Prefixed to relative URLs. Replace with your project config if needed. */
const API_BASE_URL = "";

declare const wx: {
  request(options: {
    url: string;
    method?: string;
    header?: Record<string, string>;
    data?: string;
    timeout?: number;
    success(res: { statusCode: number; data: unknown }): void;
    fail(err: { errMsg: string }): void;
  }): void;
};

/** Fetch-like HTTP call without AbortSignal; timeout is handled via wx.request. */
export function callApi(input: string, init?: CallApiInit): Promise<CallApiResponse> {
  return new Promise((resolve, reject) => {
    const url = input.startsWith("http://") || input.startsWith("https://") ? input : API_BASE_URL + input;
    wx.request({
      url,
      method: init?.method ?? "GET",
      header: init?.headers,
      data: init?.body,
      timeout: init?.timeout ?? 10000,
      success(response) {
        const status = response.statusCode;
        const body = response.data;
        const normalizedBody =
          body && typeof body === "object" && !Array.isArray(body)
            ? {
                ...(body as Record<string, unknown>),
                msg:
                  (body as Record<string, unknown>).msg ??
                  (body as Record<string, unknown>).message ??
                  "",
              }
            : body;
        resolve({
          ok: status >= 200 && status < 300,
          status,
          json: async () => normalizedBody,
        });
      },
      fail(error) {
        const timedOut = /timeout/i.test(error.errMsg);
        reject(new Error(timedOut ? "请求超时" : error.errMsg));
      },
    });
  });
}
`

func (t *TsGen) GenerateCode(mp *astinfo.MainProject) {
	outDir := basic.Cfg.Generation.TsPath
	if outDir == "" {
		return
	}
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(basic.Argument.SourcePath, outDir)
	}
	var err error
	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Printf("Failed to resolve ts gen directory: %v\n", err)
		return
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Printf("Failed to create ts gen directory: %v\n", err)
		return
	}

	// 2. Collect all services and referenced DTOs
	var allServices []*astinfo.Struct
	referencedStructs := make(map[string]*astinfo.Struct)
	referencedEnums := make(map[string]*astinfo.EnumDef)

	for _, pkgName := range mp.SortedPacakgeNames {
		pkg := mp.Packages[pkgName]
		for _, structName := range pkg.SortedStructNames {
			s := pkg.Structs[structName]
			if len(s.MethodManager.Server) == 0 {
				continue
			}
			allServices = append(allServices, s)

			for _, m := range s.MethodManager.Server {
				for _, p := range m.Params {
					t.collectStructs(p.Type, referencedStructs, mp, referencedEnums)
				}
				for _, r := range m.Results {
					t.collectStructs(r.Type, referencedStructs, mp, referencedEnums)
				}
			}
		}
	}

	sort.Slice(allServices, func(i, j int) bool {
		return allServices[i].StructName < allServices[j].StructName
	})

	if len(mp.EnumMap) > 0 {
		t.genEnumFile(outDir, mp.EnumMap)
	}
	t.genTsLibFile(outDir)
	t.genSchemaFile(outDir, referencedStructs, referencedEnums, mp)
	t.genNetworkFile(outDir, allServices, mp)
}

func (t *TsGen) genTsLibFile(outDir string) {
	path := filepath.Join(outDir, "ts-lib.gen.ts")
	if err := os.WriteFile(path, []byte(tsLibTemplate), 0644); err != nil {
		fmt.Printf("Failed to write ts-lib.gen.ts: %v\n", err)
	}
	t.writeFileIfMissing(filepath.Join(outDir, "call-api.ts"), callApiTsTemplate)
	t.writeFileIfMissing(filepath.Join(outDir, "pc.ts"), pcTsTemplate)
	t.writeFileIfMissing(filepath.Join(outDir, "wx.ts"), wxTsTemplate)
	t.writeFileIfMissing(filepath.Join(outDir, "platform.ts"), platformTsTemplate)
}

func (t *TsGen) writeFileIfMissing(path, content string) {
	if _, err := os.Stat(path); err == nil {
		return
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		fmt.Printf("Failed to write %s: %v\n", filepath.Base(path), err)
	}
}

func (t *TsGen) genEnumFile(outDir string, referencedEnums map[string]*astinfo.EnumDef) {
	os.WriteFile(filepath.Join(outDir, "enum.gen.ts"), []byte(genEnumFileContent(referencedEnums)), 0644)
}

func (t *TsGen) genSchemaFile(outDir string, referencedStructs map[string]*astinfo.Struct, referencedEnums map[string]*astinfo.EnumDef, mp *astinfo.MainProject) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	if len(referencedEnums) > 0 {
		sb.WriteString("import type { ")
		sb.WriteString(strings.Join(sortedEnumNames(referencedEnums), ", "))
		sb.WriteString(" } from \"./enum.gen\";\n")
	}
	sb.WriteString("\n")

	var structNames []string
	for name := range referencedStructs {
		structNames = append(structNames, name)
	}
	sort.Strings(structNames)

	for _, name := range structNames {
		s := referencedStructs[name]
		sb.WriteString(t.genInterface(s, mp))
		sb.WriteString("\n")
	}

	os.WriteFile(filepath.Join(outDir, "schema.gen.ts"), []byte(sb.String()), 0644)
}

func (t *TsGen) genNetworkFile(outDir string, services []*astinfo.Struct, mp *astinfo.MainProject) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import { callApi, RespClass } from \"./ts-lib.gen\";\n")

	typeNames := t.collectAllTypeNames(services, mp)
	if len(typeNames) > 0 {
		sb.WriteString("import type { ")
		sb.WriteString(strings.Join(typeNames, ", "))
		sb.WriteString(" } from \"./schema.gen\";\n")
	}
	sb.WriteString("\n")

	for _, s := range services {
		className := s.StructName
		if !strings.HasSuffix(className, "Api") {
			className += "Api"
		}
		sb.WriteString(fmt.Sprintf("export class %s {\n", className))

		methods := make([]*astinfo.Method, len(s.MethodManager.Server))
		copy(methods, s.MethodManager.Server)
		sort.Slice(methods, func(i, j int) bool {
			return methods[i].Name < methods[j].Name
		})

		for _, m := range methods {
			url := m.Comment.Url
			fullUrl := strings.ReplaceAll(filepath.Join(s.Comment.Url, url), "\\", "/")
			urlFieldName := astbasic.FirstLower(m.Name) + "Url"

			fmt.Fprintf(&sb, "  /** %s */\n", m.Comment.Title)
			fmt.Fprintf(&sb, "  static readonly %s = \"%s\";\n", urlFieldName, fullUrl)

			respType := "void"
			if len(m.Results) > 1 {
				respType = t.mapType(m.Results[0].Type)
			}

			methodName := astbasic.FirstLower(m.Name)
			fmt.Fprintf(&sb, "  /** %s */\n", m.Comment.Title)
			if len(m.Params) > 1 {
				reqType := t.mapType(m.Params[1].Type)
				fmt.Fprintf(&sb, "  async %s(req: %s): Promise<RespClass<%s>> {\n", methodName, reqType, respType)
				fmt.Fprintf(&sb, "    return callApi<%s>(%s.%s, req);\n", respType, className, urlFieldName)
			} else {
				fmt.Fprintf(&sb, "  async %s(): Promise<RespClass<%s>> {\n", methodName, respType)
				fmt.Fprintf(&sb, "    return callApi<%s>(%s.%s, {});\n", respType, className, urlFieldName)
			}
			sb.WriteString("  }\n\n")
		}
		sb.WriteString("}\n\n")
		fmt.Fprintf(&sb, "export const %s = new %s();\n\n", astbasic.FirstLower(className), className)
	}

	os.WriteFile(filepath.Join(outDir, "network.gen.ts"), []byte(sb.String()), 0644)
}

func (t *TsGen) collectAllTypeNames(services []*astinfo.Struct, mp *astinfo.MainProject) []string {
	seen := make(map[string]struct{})
	for _, s := range services {
		for _, m := range s.MethodManager.Server {
			if len(m.Params) > 1 {
				t.addTypeName(m.Params[1].Type, seen, mp)
			}
			if len(m.Results) > 1 {
				t.addTypeName(m.Results[0].Type, seen, mp)
			}
		}
	}
	var names []string
	for name := range seen {
		if name != "void" {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

func (t *TsGen) addTypeName(ty astinfo.Typer, seen map[string]struct{}, mp *astinfo.MainProject) {
	ty = astinfo.GetBasicType(ty)
	switch v := ty.(type) {
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return
		}
		seen[v.StructName] = struct{}{}
		for _, field := range v.FlatFields() {
			t.addTypeName(field.Type, seen, mp)
		}
	case *astinfo.ArrayType:
		t.addTypeName(v.Typer, seen, mp)
	case *astinfo.PointerType:
		t.addTypeName(v.Typer, seen, mp)
	case *astinfo.Alias:
		t.addTypeName(v.Typer, seen, mp)
	}
}

func (t *TsGen) collectStructs(ty astinfo.Typer, seen map[string]*astinfo.Struct, mp *astinfo.MainProject, referencedEnums map[string]*astinfo.EnumDef) {
	ty = astinfo.GetBasicType(ty)
	switch v := ty.(type) {
	case *astinfo.Struct:
		if _, ok := seen[v.StructName]; !ok {
			if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
				return
			}
			seen[v.StructName] = v
			collectReferencedEnums(v, mp, referencedEnums)
			for _, field := range v.Fields {
				t.collectStructs(field.Type, seen, mp, referencedEnums)
			}
		}
	case *astinfo.ArrayType:
		t.collectStructs(v.Typer, seen, mp, referencedEnums)
	case *astinfo.PointerType:
		t.collectStructs(v.Typer, seen, mp, referencedEnums)
	}
}

func (t *TsGen) genInterface(s *astinfo.Struct, mp *astinfo.MainProject) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "export interface %s {\n", s.StructName)

	for _, field := range s.FlatFields() {
		jsonKey := field.GetJsonName()
		if jsonKey == "" || jsonKey == "-" {
			fmt.Printf("WARNING: field %s::%s is not a JSON field\n", field.Type.IDName(), field.Name)
			continue
		}
		tsName := jsonKey
		if jsonKey == "_id" {
			tsName = "id"
		}
		tsType := mapFieldType(field, mp, t.mapType)
		if jsonKeyEpochMillisTime(jsonKey) {
			tsType = "number"
		}
		if field.Comment.CommentText != "" {
			fmt.Fprintf(&sb, "  /** %s */\n", field.Comment.CommentText)
		}
		fmt.Fprintf(&sb, "  %s: %s;\n", tsName, tsType)
	}
	sb.WriteString("}\n")
	return sb.String()
}

func jsonKeyEpochMillisTime(jsonKey string) bool {
	return strings.HasSuffix(jsonKey, "At") || strings.HasSuffix(jsonKey, "Time")
}

func (t *TsGen) mapType(ty astinfo.Typer) string {
	switch v := ty.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "string"
		case "byte", "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16":
			return "number"
		case "float32", "float64":
			return "number"
		case "bool":
			return "boolean"
		default:
			return "unknown"
		}
	case *astinfo.ArrayType:
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "string"
			}
		}
		return t.mapType(v.Typer) + "[]"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "number"
		}
		return v.StructName
	case *astinfo.PointerType:
		return t.mapType(v.Typer)
	case *astinfo.Alias:
		return t.mapType(v.Typer)
	default:
		return "unknown"
	}
}
