package ts_gen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wanjm/gos/astbasic"
	"github.com/wanjm/gos/astinfo"
	"github.com/wanjm/gos/basic"
)

type TsGen struct{}

func NewTsGen() *TsGen {
	return &TsGen{}
}

const tsLibTemplate = `// Code generated by github.com/wanjm/gos DO NOT EDIT.

interface ApiResponse<T> {
  code: number;
  msg: string;
  obj: T;
}

export class RespClass<T> {
  code: number;
  msg: string;
  body: T;

  constructor(code: number, msg: string, body: T) {
    this.code = code;
    this.msg = msg;
    this.body = body;
  }

  isSuccess(): boolean {
    return this.code === 1;
  }
}

async function httpRequest<T>(
  url: string,
  requestData: unknown,
  options: { timeout?: number } = {},
): Promise<ApiResponse<T>> {
  const timeout = options.timeout ?? 10000;
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestData),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    if (!res.ok) throw new Error("请求失败 " + res.status);
    return (await res.json()) as ApiResponse<T>;
  } catch (e) {
    const err = e as Error;
    throw new Error(err.name === "AbortError" ? "请求超时" : err.message);
  }
}

export async function callApi<T>(
  url: string,
  requestData: unknown,
): Promise<RespClass<T>> {
  try {
    const res = await httpRequest<T>(url, requestData);
    return new RespClass<T>(res.code, res.msg, res.obj);
  } catch (e) {
    const err = e as Error;
    return new RespClass<T>(-1, err.message, null as T);
  }
}
`

func (t *TsGen) GenerateCode(mp *astinfo.MainProject) {
	outDir := basic.Cfg.Generation.TsPath
	if outDir == "" {
		return
	}
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(basic.Argument.SourcePath, outDir)
	}
	var err error
	outDir, err = filepath.Abs(outDir)
	if err != nil {
		fmt.Printf("Failed to resolve ts gen directory: %v\n", err)
		return
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Printf("Failed to create ts gen directory: %v\n", err)
		return
	}

	var allServices []*astinfo.Struct
	referencedStructs := make(map[string]*astinfo.Struct)

	for _, pkgName := range mp.SortedPacakgeNames {
		pkg := mp.Packages[pkgName]
		for _, structName := range pkg.SortedStructNames {
			s := pkg.Structs[structName]
			if len(s.MethodManager.Server) == 0 {
				continue
			}
			allServices = append(allServices, s)

			for _, m := range s.MethodManager.Server {
				for _, p := range m.Params {
					t.collectStructs(p.Type, referencedStructs)
				}
				for _, r := range m.Results {
					t.collectStructs(r.Type, referencedStructs)
				}
			}
		}
	}

	sort.Slice(allServices, func(i, j int) bool {
		return allServices[i].StructName < allServices[j].StructName
	})

	t.genTsLibFile(outDir)
	t.genSchemaFile(outDir, referencedStructs)
	t.genNetworkFile(outDir, allServices)
}

func (t *TsGen) genTsLibFile(outDir string) {
	path := filepath.Join(outDir, "ts-lib.gen.ts")
	if _, err := os.Stat(path); err == nil {
		return
	}
	if err := os.WriteFile(path, []byte(tsLibTemplate), 0644); err != nil {
		fmt.Printf("Failed to write ts-lib.gen.ts: %v\n", err)
	}
}

func (t *TsGen) genSchemaFile(outDir string, referencedStructs map[string]*astinfo.Struct) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n\n")

	var structNames []string
	for name := range referencedStructs {
		structNames = append(structNames, name)
	}
	sort.Strings(structNames)

	for _, name := range structNames {
		s := referencedStructs[name]
		sb.WriteString(t.genInterface(s))
		sb.WriteString("\n")
	}

	os.WriteFile(filepath.Join(outDir, "schema.gen.ts"), []byte(sb.String()), 0644)
}

func (t *TsGen) genNetworkFile(outDir string, services []*astinfo.Struct) {
	var sb strings.Builder
	sb.WriteString("// Code generated by github.com/wanjm/gos DO NOT EDIT.\n")
	sb.WriteString("import { callApi, RespClass } from \"./ts-lib.gen\";\n")

	typeNames := t.collectAllTypeNames(services)
	if len(typeNames) > 0 {
		sb.WriteString("import type { ")
		sb.WriteString(strings.Join(typeNames, ", "))
		sb.WriteString(" } from \"./schema.gen\";\n")
	}
	sb.WriteString("\n")

	for _, s := range services {
		className := s.StructName
		if !strings.HasSuffix(className, "Api") {
			className += "Api"
		}
		sb.WriteString(fmt.Sprintf("export class %s {\n", className))

		methods := make([]*astinfo.Method, len(s.MethodManager.Server))
		copy(methods, s.MethodManager.Server)
		sort.Slice(methods, func(i, j int) bool {
			return methods[i].Name < methods[j].Name
		})

		for _, m := range methods {
			url := m.Comment.Url
			fullUrl := strings.ReplaceAll(filepath.Join(s.Comment.Url, url), "\\", "/")
			urlFieldName := astbasic.FirstLower(m.Name) + "Url"

			fmt.Fprintf(&sb, "  /** %s */\n", m.Comment.Title)
			fmt.Fprintf(&sb, "  static readonly %s = \"%s\";\n", urlFieldName, fullUrl)

			respType := "void"
			if len(m.Results) > 1 {
				respType = t.mapType(m.Results[0].Type)
			}

			methodName := astbasic.FirstLower(m.Name)
			fmt.Fprintf(&sb, "  /** %s */\n", m.Comment.Title)
			if len(m.Params) > 1 {
				reqType := t.mapType(m.Params[1].Type)
				fmt.Fprintf(&sb, "  async %s(req: %s): Promise<RespClass<%s>> {\n", methodName, reqType, respType)
				fmt.Fprintf(&sb, "    return callApi<%s>(%s.%s, req);\n", respType, className, urlFieldName)
			} else {
				fmt.Fprintf(&sb, "  async %s(): Promise<RespClass<%s>> {\n", methodName, respType)
				fmt.Fprintf(&sb, "    return callApi<%s>(%s.%s, {});\n", respType, className, urlFieldName)
			}
			sb.WriteString("  }\n\n")
		}
		sb.WriteString("}\n\n")
		fmt.Fprintf(&sb, "export const %s = new %s();\n\n", astbasic.FirstLower(className), className)
	}

	os.WriteFile(filepath.Join(outDir, "network.gen.ts"), []byte(sb.String()), 0644)
}

func (t *TsGen) collectAllTypeNames(services []*astinfo.Struct) []string {
	seen := make(map[string]struct{})
	for _, s := range services {
		for _, m := range s.MethodManager.Server {
			if len(m.Params) > 1 {
				t.addTypeName(m.Params[1].Type, seen)
			}
			if len(m.Results) > 1 {
				t.addTypeName(m.Results[0].Type, seen)
			}
		}
	}
	var names []string
	for name := range seen {
		if name != "void" {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

func (t *TsGen) addTypeName(ty astinfo.Typer, seen map[string]struct{}) {
	ty = astinfo.GetBasicType(ty)
	switch v := ty.(type) {
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return
		}
		seen[v.StructName] = struct{}{}
	case *astinfo.ArrayType:
		t.addTypeName(v.Typer, seen)
	case *astinfo.PointerType:
		t.addTypeName(v.Typer, seen)
	case *astinfo.Alias:
		t.addTypeName(v.Typer, seen)
	}
}

func (t *TsGen) collectStructs(ty astinfo.Typer, seen map[string]*astinfo.Struct) {
	ty = astinfo.GetBasicType(ty)
	switch v := ty.(type) {
	case *astinfo.Struct:
		if _, ok := seen[v.StructName]; !ok {
			if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
				return
			}
			seen[v.StructName] = v
			for _, field := range v.Fields {
				t.collectStructs(field.Type, seen)
			}
		}
	case *astinfo.ArrayType:
		t.collectStructs(v.Typer, seen)
	case *astinfo.PointerType:
		t.collectStructs(v.Typer, seen)
	}
}

func (t *TsGen) genInterface(s *astinfo.Struct) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "export interface %s {\n", s.StructName)

	for _, field := range s.FlatFields() {
		jsonKey := field.GetJsonName()
		if jsonKey == "" || jsonKey == "-" {
			fmt.Printf("WARNING: field %s::%s is not a JSON field\n", field.Type.IDName(), field.Name)
			continue
		}
		tsName := jsonKey
		if jsonKey == "_id" {
			tsName = "id"
		}
		tsType := t.mapType(field.Type)
		if jsonKeyEpochMillisTime(jsonKey) {
			tsType = "number"
		}
		if field.Comment.CommentText != "" {
			fmt.Fprintf(&sb, "  /** %s */\n", field.Comment.CommentText)
		}
		fmt.Fprintf(&sb, "  %s: %s;\n", tsName, tsType)
	}
	sb.WriteString("}\n")
	return sb.String()
}

func jsonKeyEpochMillisTime(jsonKey string) bool {
	return strings.HasSuffix(jsonKey, "At") || strings.HasSuffix(jsonKey, "Time")
}

func (t *TsGen) mapType(ty astinfo.Typer) string {
	switch v := ty.(type) {
	case *astinfo.RawType:
		switch v.IDName() {
		case "string":
			return "string"
		case "byte", "int", "int8", "int16", "int32", "int64", "uint", "uint32", "uint64", "uint8", "uint16":
			return "number"
		case "float32", "float64":
			return "number"
		case "bool":
			return "boolean"
		default:
			return "unknown"
		}
	case *astinfo.ArrayType:
		elem := astinfo.GetBasicType(v.Typer)
		if raw, ok := elem.(*astinfo.RawType); ok {
			if id := raw.IDName(); id == "byte" || id == "uint8" {
				return "string"
			}
		}
		return t.mapType(v.Typer) + "[]"
	case *astinfo.Struct:
		if v.StructName == "Time" && v.GoSource.Pkg.ModPath == "time" {
			return "number"
		}
		return v.StructName
	case *astinfo.PointerType:
		return t.mapType(v.Typer)
	case *astinfo.Alias:
		return t.mapType(v.Typer)
	default:
		return "unknown"
	}
}
